
import __ASTRO_IMAGE_IMPORT_1lpHDm from "../../../images/pepr-dashboard-screenshot.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fpepr-tutorials%2Fcreate-pepr-dashboard.md";
import __ASTRO_IMAGE_IMPORT_ZojHIb from "../../../images/admission-endpoint.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fpepr-tutorials%2Fcreate-pepr-dashboard.md";
import __ASTRO_IMAGE_IMPORT_1ukj0U from "../../../images/watcher-endpoint.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fpepr-tutorials%2Fcreate-pepr-dashboard.md";
import __ASTRO_IMAGE_IMPORT_1FQbhO from "../../../images/pepr-dashboard-screenshot.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fv0.53%2Fpepr-tutorials%2Fcreate-pepr-dashboard.md";
import __ASTRO_IMAGE_IMPORT_1CVC2U from "../../../images/admission-endpoint.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fv0.53%2Fpepr-tutorials%2Fcreate-pepr-dashboard.md";
import __ASTRO_IMAGE_IMPORT_Z1IYMgg from "../../../images/watcher-endpoint.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fv0.53%2Fpepr-tutorials%2Fcreate-pepr-dashboard.md";
import __ASTRO_IMAGE_IMPORT_ZjXG8D from "../../../images/pepr-dashboard-screenshot.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fv0.54%2Fpepr-tutorials%2Fcreate-pepr-dashboard.md";
import __ASTRO_IMAGE_IMPORT_ZmSfnx from "../../../images/admission-endpoint.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fv0.54%2Fpepr-tutorials%2Fcreate-pepr-dashboard.md";
import __ASTRO_IMAGE_IMPORT_1kmt7d from "../../../images/watcher-endpoint.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fv0.54%2Fpepr-tutorials%2Fcreate-pepr-dashboard.md";
export default new Map([["../../../images/pepr-dashboard-screenshot.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fpepr-tutorials%2Fcreate-pepr-dashboard.md", __ASTRO_IMAGE_IMPORT_1lpHDm], ["../../../images/admission-endpoint.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fpepr-tutorials%2Fcreate-pepr-dashboard.md", __ASTRO_IMAGE_IMPORT_ZojHIb], ["../../../images/watcher-endpoint.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fpepr-tutorials%2Fcreate-pepr-dashboard.md", __ASTRO_IMAGE_IMPORT_1ukj0U], ["../../../images/pepr-dashboard-screenshot.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fv0.53%2Fpepr-tutorials%2Fcreate-pepr-dashboard.md", __ASTRO_IMAGE_IMPORT_1FQbhO], ["../../../images/admission-endpoint.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fv0.53%2Fpepr-tutorials%2Fcreate-pepr-dashboard.md", __ASTRO_IMAGE_IMPORT_1CVC2U], ["../../../images/watcher-endpoint.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fv0.53%2Fpepr-tutorials%2Fcreate-pepr-dashboard.md", __ASTRO_IMAGE_IMPORT_Z1IYMgg], ["../../../images/pepr-dashboard-screenshot.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fv0.54%2Fpepr-tutorials%2Fcreate-pepr-dashboard.md", __ASTRO_IMAGE_IMPORT_ZjXG8D], ["../../../images/admission-endpoint.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fv0.54%2Fpepr-tutorials%2Fcreate-pepr-dashboard.md", __ASTRO_IMAGE_IMPORT_ZmSfnx], ["../../../images/watcher-endpoint.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fv0.54%2Fpepr-tutorials%2Fcreate-pepr-dashboard.md", __ASTRO_IMAGE_IMPORT_1kmt7d]]);
		